// <auto-generated />
using System;
using Angular7DemoServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angular7DemoServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200224203525_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Angular7DemoServices.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fname");

                    b.Property<int?>("IDDocument");

                    b.Property<string>("Lname");

                    b.Property<string>("email");

                    b.Property<string>("gender");

                    b.HasKey("ID");

                    b.ToTable("tblemployee");

                    b.HasData(
                        new { ID = 1, Fname = "SystemTenant", Lname = "G", email = "Mangesh.g@outlook.com", gender = "1" }
                    );
                });

            modelBuilder.Entity("Angular7DemoServices.FileToUpload", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileAsBase64");

                    b.Property<byte[]>("FileAsByteArray");

                    b.Property<string>("FileName");

                    b.Property<string>("FileSize");

                    b.Property<string>("FileType");

                    b.Property<int>("IDEmployee");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<long>("LastModifiedTime");

                    b.HasKey("ID");

                    b.ToTable("document");

                    b.HasData(
                        new { ID = 1, FileAsBase64 = "", FileName = "", FileSize = "", FileType = "", IDEmployee = 0, LastModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), LastModifiedTime = 0L }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
